### ISSUE TITLE
Breaks on EC2 key pair creation

### ISSUE THREAD

**Issue by SMR39** [dcos-labs/dcos-bootstrap#3]
```
TASK: [Create EC2 key pair] ***************************************************
failed: [localhost] => (item=ssh-rsa  key - displayed ################################################################################################################################################################################################################################################################################################################# ###) => {"failed": true, "item": "ssh-rsa ##################################################################################################################################################################################################################################################################################################################", "parsed": false}
Traceback (most recent call last):
  File "/Users/shashiravula/.ansible/tmp/ansible-tmp-1455954629.91-214428181746625/ec2_key", line 2045, in <module>
    main()
  File "/Users/shashiravula/.ansible/tmp/ansible-tmp-1455954629.91-214428181746625/ec2_key", line 121, in main
    key = ec2.get_key_pair(name)
  File "/Library/Python/2.7/site-packages/boto-2.39.0-py2.7.egg/boto/ec2/connection.py", line 2855, in get_key_pair
    dry_run=dry_run
  File "/Library/Python/2.7/site-packages/boto-2.39.0-py2.7.egg/boto/ec2/connection.py", line 2837, in get_all_key_pairs
    [('item', KeyPair)], verb='POST')
  File "/Library/Python/2.7/site-packages/boto-2.39.0-py2.7.egg/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>76833b79-9de1-4eb5-aa2e-4f4195096c9f</RequestID></Response>


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/shashiravula/bootstrap.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1

make: *** [bootstrap] Error 2

```

@mlafeldt I am running on MAC OS X and even had manually install few tools to venv .But it seem to skip the requirements and execute ansible playbook . It hangs at ec2 key pair creation.

but i manually ran those requirements and ..when i run pip install pycrpto 

```
Command "/System/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/qb/_78xhkhj1cd4dz64gh720x5r0000gn/T/pip-build-vdsGXI/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/qb/_78xhkhj1cd4dz64gh720x5r0000gn/T/pip-LY6KKB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/qb/_78xhkhj1cd4dz64gh720x5r0000gn/T/pip-build-vdsGXI/pycrypto 

```

error is thrown .. installing it using pip 2.6 
I have also tried to run in ubuntu and centos and same error  thrown when pycrypto is being installed .

**Comment by mlafeldt** [comment]
@SMR39 The error message "You are not authorized to perform this operation" tells me that you're not allowed to add your SSH key to AWS. I suggest to check your AWS credentials.

**Comment by rprakashg** [comment]
How do I specify a key that I already have, I don't want the ssh key to be added to AWS. Is that supported?
